### ISSUE TITLE
JobGroupTest.testJoinIfJobCoundExceedsSeedCount fails sporadically

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.runtime#11]
Test fails sporadically, introduced in #7 
```
junit.framework.AssertionFailedError: Job result in unexpected order expected:<1> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.TestCase.assertEquals(TestCase.java:377)
	at org.eclipse.core.tests.runtime.jobs.JobGroupTest.testJoinIfJobCoundExceedsSeedCount(JobGroupTest.java:802)
```

**Comment by iloveeclipse** [comment]
Should be stable now
