### ISSUE TITLE
EclipsePreferencesTest fails since I20220414-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.runtime#25]
There is a new test fail caused by [this](https://github.com/eclipse-equinox/equinox.bundles/pull/15) change, tests must be updated too.

https://download.eclipse.org/eclipse/downloads/drops4/I20220414-1800/testresults/html/org.eclipse.core.tests.runtime_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

```
org.eclipse.core.tests.internal.preferences.EclipsePreferencesTest | testLegacy | Failure | 
3.0 expected:<value.1649981901638-0.3893493642818254> but was:<null>junit.framework.ComparisonFailure: 3.0 expected:<value.1649981901638-0.3893493642818254> but was:<null>at junit.framework.Assert.assertEquals(Assert.java:100)at junit.framework.TestCase.assertEquals(TestCase.java:253)at org.eclipse.core.tests.internal.preferences.EclipsePreferencesTest.testLegacy(EclipsePreferencesTest.java:1091)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

_Originally posted by @iloveeclipse in https://github.com/eclipse-equinox/equinox.bundles/issues/15#issuecomment-1100284364_

**Comment by iloveeclipse** [comment]
No fail in https://download.eclipse.org/eclipse/downloads/drops4/I20220415-1800/testResults.php
