### ISSUE TITLE
JobTest.testAsynchJobConflict failure 

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.runtime#29]
See https://download.eclipse.org/eclipse/downloads/drops4/I20220418-1800/testresults/html/org.eclipse.core.tests.runtime_ep424I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

```
JobTest | testAsynchJobConflict | Failure | 11.3 expected:<0> but was:<4>
junit.framework.AssertionFailedError: 11.3 expected:<0> but was:<4>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)at junit.framework.TestCase.assertEquals(TestCase.java:377)
at org.eclipse.core.tests.runtime.jobs.JobTest.testAsynchJobConflict(JobTest.java:357)
```
Looks like a regression from #17 , the runtime tests were stable AFAIK.

**Comment by mickaelistria** [comment]
@jukzi Can you please investigate that and confirm whether it is a regression from #17 ?

**Comment by jukzi** [comment]
it's just random. i can reproduce it locally on win with a chance of ~2%
```
public class RepeatedTestSuite extends TestCase {
    public static Test suite() {
        TestSuite suite = new TestSuite(RepeatedTestSuite.class.getName());

		for (int i = 0; i < 1000; i++) {
			suite.addTestSuite(MarkerTest.class); // the test to repeat
        }
        return suite;
    }
}
```

**Comment by mickaelistria** [comment]
@jukzi Thanks. Are those ~2% failures the number with and/or without patch #17 ?
