### ISSUE TITLE
random failing org.eclipse.core.tests.runtime.jobs.JobGroupTest.testJoinWithTimeout

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.runtime#60]
https://download.eclipse.org/eclipse/downloads/drops4/I20220522-0600/testresults/html/org.eclipse.core.tests.runtime_ep424I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

```
junit.framework.AssertionFailedError: 2.0
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.core.tests.runtime.jobs.JobGroupTest.testJoinWithTimeout(JobGroupTest.java:540)
```

**Comment by jukzi** [comment]
also
https://download.eclipse.org/eclipse/downloads/drops4/I20220605-1800/testresults/html/org.eclipse.core.tests.runtime_ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html
